const Songs = [
    {
        id: 0,
        favourite: false,
        SongName: "Raata lambiya",
        artist: "Asees Kaur",
        song: "https://firebasestorage.googleapis.com/v0/b/react-music-player-5aaa7.appspot.com/o/Songs%2FRaatan%20Lambiyan_320(PagalWorld.com.se).mp3?alt=media&token=7c4b2a4a-fec3-4839-8e53-6d7c7d41862d",
        img_src: "https://firebasestorage.googleapis.com/v0/b/react-music-player-5aaa7.appspot.com/o/images%2Fraata%20lambiya.jpg?alt=media&token=4a4bb9d1-9463-418d-aee1-898526e29243",
        genre: 'bollywood',
        movieName:"Shershaah",
    },
    {
        id: 1,
        favourite: false,
        SongName: "Kesariya",
        artist: "Arijit Singh",
        song: "https://firebasestorage.googleapis.com/v0/b/react-music-player-5aaa7.appspot.com/o/Songs%2FKesariya_320(PagalWorld.com.se).mp3?alt=media&token=f1971bf3-893d-4304-9ec1-4100ed949c4c",
        img_src: "https://firebasestorage.googleapis.com/v0/b/react-music-player-5aaa7.appspot.com/o/images%2Fkesariya.jfif?alt=media&token=7260741f-9050-455d-9bba-dbbd4fff4681",
        genre: 'bollywood',
        movieName:"Brahmastra ",
    },
    {
        id: 2,
        favourite: false,
        SongName: "Tere Pyaar mei",
        artist: "Arijit Singh and Nikhita Gandhi",
        song: "https://firebasestorage.googleapis.com/v0/b/react-music-player-5aaa7.appspot.com/o/Songs%2FTere%20Pyar%20Mein_320(PagalWorld.com.se).mp3?alt=media&token=00a4e541-730c-494e-a82e-d7c8a1a99537",
        img_src: "https://firebasestorage.googleapis.com/v0/b/react-music-player-5aaa7.appspot.com/o/images%2Ftu%20jhuti%20me%20makkar.jfif?alt=media&token=f8c48e10-3b6b-4874-b5f2-30ded346f9c7",
        genre: 'bollywood',
        movieName:"Tu Jhoothi Main Makkaar",
    },
    {
        id: 3,
        favourite: false,
        SongName: "Dil Glati kar betha hai",
        artist: "Jubin Nautiyal",
        song: "https://firebasestorage.googleapis.com/v0/b/react-music-player-5aaa7.appspot.com/o/Songs%2FDil%20Galti%20Kar%20Baitha%20Hai_320(PagalWorld.com.se).mp3?alt=media&token=a50bd263-aa90-47e3-9871-0f3f48795541",
        img_src: "https://firebasestorage.googleapis.com/v0/b/react-music-player-5aaa7.appspot.com/o/images%2Fdil%20galti%20kar.jpg?alt=media&token=64b08e7b-e627-4722-a814-f678914ccf6c",
        genre: 'bollywood',
        movieName:"",
    },
    {
        id: 4,
        favourite: false,
        SongName: "Kahani Suno",
        artist: "Kaifi Khalil and Vir Rapstar",
        song: "https://firebasestorage.googleapis.com/v0/b/react-music-player-5aaa7.appspot.com/o/Songs%2FKahani%20Suno_320(PagalWorld.com.se).mp3?alt=media&token=cb983887-a292-4a6a-98fb-8aa808f570e5",
        img_src: "https://firebasestorage.googleapis.com/v0/b/react-music-player-5aaa7.appspot.com/o/images%2Fkahani%20suno.jpg?alt=media&token=37608ac9-d138-49a4-8237-b479e2a1d2c4",
        genre: 'bollywood',
        movieName:"Mujhe Pyaar Hua Tha",
    },

    {
        id: 5,
        favourite: false,
        SongName: "Meri Zindagi Hai Tu",
        artist: "Jubin Nautiyal and Neeti Mohan",
        song: "https://firebasestorage.googleapis.com/v0/b/react-music-player-5aaa7.appspot.com/o/Songs%2FMeri%20Zindagi%20Hai%20Tu_320(PagalWorld.com.se).mp3?alt=media&token=773494b4-2157-40ae-a6eb-12c395b89bdb",
        img_src: "https://firebasestorage.googleapis.com/v0/b/react-music-player-5aaa7.appspot.com/o/images%2FMeri%20Zindagi%20Hai%20Tu.jpg?alt=media&token=450cd434-694c-49ef-b36c-464b946b0a14",
        genre: 'bollywood',
        movieName:"Satyameva Jayate 2",
    },
    {
        id: 6,
        favourite: false,
        SongName: "Pehli Pehli Baarish",
        artist: "Yasser Desai",
        song: "https://firebasestorage.googleapis.com/v0/b/react-music-player-5aaa7.appspot.com/o/Songs%2FPehli%20Pehli%20Baarish_320(PagalWorld.com.se).mp3?alt=media&token=1994fdc2-3a96-4b31-a326-c9f38ac292be",
        img_src: "https://firebasestorage.googleapis.com/v0/b/react-music-player-5aaa7.appspot.com/o/images%2FPehli%20Pehli%20Baarish.jpg?alt=media&token=2b2fcfe9-8424-44f1-94ea-e82ba5e9b9f2",
        genre: 'bollywood',
        movieName:"",
    },
    {
        id: 7,
        favourite: false,
        SongName: "Maan Meri Jaan",
        artist: "King",
        song: "https://firebasestorage.googleapis.com/v0/b/react-music-player-5aaa7.appspot.com/o/Songs%2FMaan%20Meri%20Jaan_320(PagalWorld.com.se)%20(1).mp3?alt=media&token=53e6b34e-9e65-455b-941a-a1d8c1fd3898",
        img_src: "https://firebasestorage.googleapis.com/v0/b/react-music-player-5aaa7.appspot.com/o/images%2Fmaan%20meri%20jaan.jpg?alt=media&token=72b09ebf-135e-4872-8fec-1b041d9e8d68",
        genre: 'bollywood',
        movieName:"",
    },
    {
        id: 8,
        favourite: false,
        SongName: "O bedardi..",
        artist: "Arijit Singh",
        song: "https://firebasestorage.googleapis.com/v0/b/react-music-player-5aaa7.appspot.com/o/Songs%2FO%20Bedardi_320(PagalWorld.com.se).mp3?alt=media&token=cf304321-7c3f-4b29-a606-d3a880ae8378",
        img_src: "https://firebasestorage.googleapis.com/v0/b/react-music-player-5aaa7.appspot.com/o/images%2Fo%20bedardiya.jpg?alt=media&token=6210089e-4165-4c3c-b782-0e033f90494a",
        genre: 'bollywood',
        movieName:"Tu Jhoothi Main Makkaar",
    },
    {
        id: 9,
        favourite: false,
        SongName: "Pyaar Hota Kai baar Hai",
        artist: "Arijit Singh",
        song: "https://firebasestorage.googleapis.com/v0/b/react-music-player-5aaa7.appspot.com/o/Songs%2FPyaar%20Hota%20Kayi%20Baar%20Hai_320(PagalWorld.com.se).mp3?alt=media&token=3b2e28b5-6fb4-4646-a8c9-f415bd3e9d4c",
        img_src: "https://firebasestorage.googleapis.com/v0/b/react-music-player-5aaa7.appspot.com/o/images%2Fpyar%20hota%20kai%20baar%20h.jfif?alt=media&token=fb67331a-74ad-4fcc-a745-fb1371e9bc49",
        genre: 'bollywood',
        movieName:"Tu Jhoothi Main Makkaar",
    },
    {
        id: 10,
        favourite: false,
        SongName: "Bekhayali",
        artist: "Arijit Singh",
        song: "https://firebasestorage.googleapis.com/v0/b/react-music-player-5aaa7.appspot.com/o/Songs%2FBekhayali-b-Arijit-Singh-Version-(pagalworldsongs.co.in).mp3?alt=media&token=2b047276-8e23-4530-a550-f1db7a60b43c",
        img_src: "https://firebasestorage.googleapis.com/v0/b/react-music-player-5aaa7.appspot.com/o/images%2FBekhayali.jpg?alt=media&token=77525a6d-5044-4ea3-9e36-6f6c12a13ea6",
        genre: 'bollywood',
        movieName:"Kabir Singh",
    },

    {
        id: 11,
        favourite: false,
        SongName: "Sanu Kehndi",
        artist: "Romy, Brijesh Shandilya",
        song: "https://firebasestorage.googleapis.com/v0/b/react-music-player-5aaa7.appspot.com/o/Songs%2FSanu-Kehndi-b-Kesari-(pagalworldsongs.co.in).mp3?alt=media&token=5b97871d-5376-4d6e-bd9d-b7dd4fc3e3dd",
        img_src: "https://firebasestorage.googleapis.com/v0/b/react-music-player-5aaa7.appspot.com/o/images%2FSanu-Kehndi.jpg?alt=media&token=b8809d1a-c53d-4d1e-8b0c-7717822c04cd",
        genre: 'bollywood',
        movieName:"Kesari",
    },

    
    {
        id: 12,
        favourite: false,
        SongName: "Mere Sohneya.",
        artist: "Sachet Tandon, Parampara Thakur, Sachet-Parampara",
        song: "https://firebasestorage.googleapis.com/v0/b/react-music-player-5aaa7.appspot.com/o/Songs%2FMere-Sohneya-b-Kabir-Singh-(pagalworldsongs.co.in).mp3?alt=media&token=65c3e316-a2f9-416d-8255-4c05e1a2807b",
        img_src: "https://firebasestorage.googleapis.com/v0/b/react-music-player-5aaa7.appspot.com/o/images%2FMere%20Sohneya.jpg?alt=media&token=ff7c5d23-79d8-43c8-b07e-a122ba0e4f4c",
        genre: 'bollywood',
        movieName:"Kabir Singh",
    },
    {
        id: 13,
        favourite: false,
        SongName: "Tujhe Kitna Chahne Lage Hum",
        artist: "Arijit Singh",
        song: "https://firebasestorage.googleapis.com/v0/b/react-music-player-5aaa7.appspot.com/o/Songs%2FTujhe-Kitna-Chahne-Lage-b-Kabir-Singh-(pagalworldsongs.co.in).mp3?alt=media&token=20636816-29c0-4247-bbfd-94620a05794d",
        img_src: "https://firebasestorage.googleapis.com/v0/b/react-music-player-5aaa7.appspot.com/o/images%2FTujhe%20Kitna%20Chahne%20Lage.jpg?alt=media&token=40349660-813d-454a-84bb-dc934d307bed",
        genre: 'bollywood',
        movieName:"Kabir Singh",
    },
    
    {
        id: 14,
        favourite: false,
        SongName: "Tera Ban Jaunga",
        artist: "Akhil Sachdeva, Tulsi Kumar",
        song: "https://firebasestorage.googleapis.com/v0/b/react-music-player-5aaa7.appspot.com/o/Songs%2FTera-Ban-Jaunga-b-Kabir-Singh-(pagalworldsongs.co.in).mp3?alt=media&token=1f9fff58-ca48-4a34-9523-415656dc2a70",
        img_src: "https://firebasestorage.googleapis.com/v0/b/react-music-player-5aaa7.appspot.com/o/images%2FTera%20Ban%20Jaunga.jpg?alt=media&token=d36edd36-38d6-4eb0-bf67-b13313ef7e98",
        genre: 'bollywood',
        movieName:"Kabir Singh",
    },
   
    {
        id: 15,
        favourite: false,
        SongName: "Teri Mitti",
        artist: "B Praak",
        song: "https://firebasestorage.googleapis.com/v0/b/react-music-player-5aaa7.appspot.com/o/Songs%2FTeri-Mitti-b-Kesari-(pagalworldsongs.co.in).mp3?alt=media&token=666d7ac8-d2a3-4890-b6f5-26f8505c4b8c",
        img_src: "https://firebasestorage.googleapis.com/v0/b/react-music-player-5aaa7.appspot.com/o/images%2Fteri%20mitti.jpg?alt=media&token=f6968361-0957-41a6-849c-5d93758cbdd6",
        genre: 'bollywood',
        movieName:"Kesari",
    },
    {
        id: 16,
        favourite: false,
        SongName: "Yeh Aaina",
        artist: "Shreya Ghoshal",
        song: "https://firebasestorage.googleapis.com/v0/b/react-music-player-5aaa7.appspot.com/o/Songs%2FYeh-Aaina-b-Kabir-Singh-(pagalworldsongs.co.in).mp3?alt=media&token=b04e698d-8c04-4f01-b84b-dd5ead3b6318",
        img_src: "https://firebasestorage.googleapis.com/v0/b/react-music-player-5aaa7.appspot.com/o/images%2FYeh%20Aaina.jpg?alt=media&token=6f0ead4d-dca7-4183-97a8-124f9127472a",
        genre: 'bollywood',
        movieName:"Kabir Singh",
    },

    {
        id: 17,
        favourite: false,
        SongName: "Ve Maahi",
        artist: "Arijit Singh, Asees Kaur",
        song: "https://firebasestorage.googleapis.com/v0/b/react-music-player-5aaa7.appspot.com/o/Songs%2FVe-Maahi-b-Kesari-(pagalworldsongs.co.in).mp3?alt=media&token=9fadf0b7-82b8-485b-af37-84582c1ea954",
        img_src: "https://firebasestorage.googleapis.com/v0/b/react-music-player-5aaa7.appspot.com/o/images%2Fve%20maahi.jpg?alt=media&token=8d927355-8e31-46f3-87db-a369d7bbb35c",
        genre: 'bollywood',
        movieName:"Kesari",
    },
    {
        id: 18,
        favourite: false,
        SongName: "Kaise Hua",
        artist: "Vishal Mishra",
        song: "https://firebasestorage.googleapis.com/v0/b/react-music-player-5aaa7.appspot.com/o/Songs%2FKaise-Hua-b-Kabir-Singh-(pagalworldsongs.co.in).mp3?alt=media&token=92532bf2-c027-4893-92b7-a9bb2875b6cf",
        img_src: "https://firebasestorage.googleapis.com/v0/b/react-music-player-5aaa7.appspot.com/o/images%2FKaise%20Hua.jpg?alt=media&token=97c29128-305f-45c2-a09a-8b446e5b6e6b",
        genre: 'bollywood',
        movieName:"Kabir Singh",
    },


    {
        id: 19,
        favourite: false,
        SongName: "Kalank",
        artist: "Arijit Singh, Shilpa Roa",
        song: "https://firebasestorage.googleapis.com/v0/b/react-music-player-5aaa7.appspot.com/o/Songs%2FKalank-b-Bonus-Track-(pagalworldsongs.co.in).mp3?alt=media&token=98a2aa65-2aae-471a-8e40-b4ae5f571d67",
        img_src: "https://firebasestorage.googleapis.com/v0/b/react-music-player-5aaa7.appspot.com/o/images%2Fkalank.jpg?alt=media&token=74d0c592-b1bf-4354-a4f9-95fb7c364768",
        genre: 'bollywood',
        movieName:"Kalank",
    },
    {
        id: 20,
        favourite: false,
        SongName: "Woh Din",
        artist: "Tushar Joshi, Pritam Chakrabarti",
        song: "https://firebasestorage.googleapis.com/v0/b/react-music-player-5aaa7.appspot.com/o/Songs%2FWoh-Din-b-Arijit-Singh-Version-(pagalworldsongs.co.in).mp3?alt=media&token=42189640-fe82-4f8f-89f5-a62332af62a9",
        img_src: "https://firebasestorage.googleapis.com/v0/b/react-music-player-5aaa7.appspot.com/o/images%2Fwoh%20din.jpg?alt=media&token=3955a6b4-5abb-4ffb-8b57-4e99d5fccb5e",
        genre: 'bollywood',
        movieName:"Chhichhore",
    },

    {
        id: 21,
        favourite: false,
        SongName: "Tabaah Ho Gaye",
        artist: "Shreya Ghoshal",
        song: "https://firebasestorage.googleapis.com/v0/b/react-music-player-5aaa7.appspot.com/o/Songs%2FTabaah-Ho-Gaye-b-Kalank-(pagalworldsongs.co.in).mp3?alt=media&token=ab518f33-d260-44ad-bf4b-4872fe160b94",
        img_src: "https://firebasestorage.googleapis.com/v0/b/react-music-player-5aaa7.appspot.com/o/images%2FTabaah-Ho-Gaye.jpg?alt=media&token=2b5b3597-1b40-4b5d-be4e-394b9221810f",
        genre: 'bollywood',
        movieName:"Kalank",
    },

    {
        id: 22,
        favourite: false,
        SongName: "Ghar More Pardesiya",
        artist: "Shreya Ghoshal",
        song: "https://firebasestorage.googleapis.com/v0/b/react-music-player-5aaa7.appspot.com/o/Songs%2FGhar-More-Pardesiya-b-Radio-Edit-(pagalworldsongs.co.in).mp3?alt=media&token=bfe0e2a6-6804-46da-b426-72c6024c97c2",
        img_src: "https://firebasestorage.googleapis.com/v0/b/react-music-player-5aaa7.appspot.com/o/images%2Fghar%20more%20pardesi.jpg?alt=media&token=2186f78b-ae01-45ba-8c32-bc850ba66803",
        genre: 'bollywood',
        movieName:"Kalank",
    },

    {
        id: 23,
        favourite: false,
        SongName: "Dance Basanti",
        artist: "Anushka Manchanda,Sachin-Jigar,Anushka Manchanda,Vishal Dadlani,Vishal Dadlani,Sachin-Jigar",
        song: "https://firebasestorage.googleapis.com/v0/b/react-music-player-5aaa7.appspot.com/o/Songs%2FDance-Basanti-(Ungli)-%5Bpagalworldsongs.co.in%5D-(pagalworldsongs.co.in).mp3?alt=media&token=7274a407-8ab1-48ff-b2b5-7e0b29034d10",
        img_src: "https://firebasestorage.googleapis.com/v0/b/react-music-player-5aaa7.appspot.com/o/images%2Fdance%20basanti.jpg?alt=media&token=625826df-9422-4e47-987c-b7eb26eb0272",
        genre: 'bollywood',
        movieName:"Ungli",
    },

    
    {
        id: 24,
        favourite: false,
        SongName: "Tere Bina Jeena",
        artist: "Abhijeet Srivastava",
        song: "https://firebasestorage.googleapis.com/v0/b/react-music-player-5aaa7.appspot.com/o/Songs%2FTere-Bina-Jeena-Saza-Ho-Gaya-b-Rooh-(pagalworldsongs.co.in).mp3?alt=media&token=f4b0d9b8-3ea2-44be-99b7-6dfd9cda5c6d",
        img_src: "https://firebasestorage.googleapis.com/v0/b/react-music-player-5aaa7.appspot.com/o/images%2Ftere%20bina%20jeena.jpg?alt=media&token=b45e12fc-ebd0-4eb8-aff2-a9354c923160",
        genre: 'bollywood',
        movieName:"Bin Roye",
    },
    {
        id: 25,
        favourite: false,
        SongName: "Fark Nahi Padta",
        artist: "Sachin-Jigar, Nikhil Paul George & DRV",
        song: "https://firebasestorage.googleapis.com/v0/b/react-music-player-5aaa7.appspot.com/o/Songs%2FFarkNahiPadtaSachinJigarNikhilPaulGeorgeDRV160kbps.mp3?alt=media&token=6f4943bb-36ea-4c7a-a9ad-dc2f90ea3333",
        img_src: "https://firebasestorage.googleapis.com/v0/b/react-music-player-5aaa7.appspot.com/o/images%2Ffarak%20nahi%20padta-farzi.jfif?alt=media&token=7f262c8a-2900-4e5d-be2a-246dd6ba0442",
        genre: 'bollywood',
        movieName:"Farzi",
    },

    {
        id: 26,
        favourite: false,
        SongName: "Sooraj Doba Hai",
        artist: "Aditi Sing Sharma, Amaal Mallik, Arijit Singh",
        song: "https://firebasestorage.googleapis.com/v0/b/react-music-player-5aaa7.appspot.com/o/Songs%2FSooraj-Dooba-Hain-(Duet-Version)-b-Roy--%5Bpagalworldsongs.co.in%5D-(pagalworldsongs.co.in).mp3?alt=media&token=08c77c51-45df-4954-8ed7-4bc057677b06",
        img_src: "https://firebasestorage.googleapis.com/v0/b/react-music-player-5aaa7.appspot.com/o/images%2Fsooraj%20dooba%20hai.jpg?alt=media&token=3f20bf8b-e854-4dbb-9bf3-7366bc8dd230",
        genre: 'bollywood',
        movieName:"Roy",
    },
    {
        id: 27,
        favourite: false,
        SongName: "Speaker Phat Jaye",
        artist: "Abuzar Akhtar,Jonita Gandhi,Aditi Singh Sharma,Harrdy Sandhu",
        song: "https://firebasestorage.googleapis.com/v0/b/react-music-player-5aaa7.appspot.com/o/Songs%2FSpeaker-Phat-Jaaye-b-Total-Dhamaal-(pagalworldsongs.co.in).mp3?alt=media&token=f81df1a1-5ec5-444a-b9a0-d402057f96a0",
        img_src: "https://firebasestorage.googleapis.com/v0/b/react-music-player-5aaa7.appspot.com/o/images%2Fspeaker%20phat%20jaye.jpg?alt=media&token=caf835cb-c427-4b68-a6e5-36f6f08658eb",
        genre: 'bollywood',
        movieName:"Total Dhamaal",
    },
    {
        id: 28,
        favourite: false,
        SongName: "Aashiq Surrender Hua",
        artist: "Amaal Mallik, Shreya Ghoshal",
        song: "https://firebasestorage.googleapis.com/v0/b/react-music-player-5aaa7.appspot.com/o/Songs%2FAashiq-Surrender-Hua-(pagalworldsongs.co.in).mp3?alt=media&token=6825bc72-134e-4406-be15-7b195482134e",
        img_src: "https://firebasestorage.googleapis.com/v0/b/react-music-player-5aaa7.appspot.com/o/images%2FAashiq-Surrender-Hua.jpg?alt=media&token=38796b66-6aff-44f2-8155-ce0c3367af24",
        genre: 'bollywood',
        movieName:"Badrinath Ki Dulhania",
    },

    {
        id: 29,
        favourite: false,
        SongName: "Pal",
        artist: "Arijit Singh",
        song: "https://firebasestorage.googleapis.com/v0/b/react-music-player-5aaa7.appspot.com/o/Songs%2FPal-b-Monsoon-Shootout-(pagalworldsongs.co.in).mp3?alt=media&token=75f57e6b-b5a3-4e96-bc62-ab109988c96b",
        img_src: "https://firebasestorage.googleapis.com/v0/b/react-music-player-5aaa7.appspot.com/o/images%2Fpal%20kesa%20pal.jpg?alt=media&token=36dcb7d4-0b4e-423d-bfae-62be4913e769",
        genre: 'bollywood',
        movieName:"Jalebi",
    },
    {
        id: 30,
        favourite: false,
        SongName: "Mene Tujhko Dekha",
        artist: "Sukriti Kakar, Nerraj Shridhav",
        song: "https://firebasestorage.googleapis.com/v0/b/react-music-player-5aaa7.appspot.com/o/Songs%2FMaine-Tujhko-Dekha-b-Golmaal-Again-(pagalworldsongs.co.in).mp3?alt=media&token=bec1255a-299f-4153-964a-a4fda2756991",
        img_src: "https://firebasestorage.googleapis.com/v0/b/react-music-player-5aaa7.appspot.com/o/images%2Fmene%20tujhko%20dekha.jpg?alt=media&token=89609d85-8249-492b-95f7-27ecda374357",
        genre: 'bollywood',
        movieName:"Golmaal Again",
    },
    {
        id: 31,
        favourite: false,
        SongName: "Swag Se Swagat",
        artist: "Neha Bhasin,Vishal Dadlani",
        song: "https://firebasestorage.googleapis.com/v0/b/react-music-player-5aaa7.appspot.com/o/Songs%2FSwag-Se-Swagat-b-Tiger-Zinda-Hai-(pagalworldsongs.co.in).mp3?alt=media&token=8e8287c8-d942-4225-9a2c-1b067d612773",
        img_src: "https://firebasestorage.googleapis.com/v0/b/react-music-player-5aaa7.appspot.com/o/images%2Fswag%20se%20karenge.jpg?alt=media&token=c1c39fe6-125e-41b7-b061-038ff3f659f7",
        genre: 'bollywood',
        movieName:"Tiger Zinda Hai",
    },
    {
        id: 32,
        favourite: false,
        SongName: "The Hook Up Song",
        artist: "Neha Kakkar,Shekhar Ravjiani,Vishal-Shekhar",
        song: "https://firebasestorage.googleapis.com/v0/b/react-music-player-5aaa7.appspot.com/o/Songs%2FThe-Hook-Up-Song-b-SOTY-2-(pagalworldsongs.co.in).mp3?alt=media&token=9bc9643c-bc46-4ee4-b068-dc1cab7692a7",
        img_src: "https://firebasestorage.googleapis.com/v0/b/react-music-player-5aaa7.appspot.com/o/images%2Fthe%20hookup%20song.jpg?alt=media&token=35f7c02b-538b-4352-8f69-00e2f25ff17b",
        genre: 'bollywood',
        movieName:"Student Of The Year 2",
    },
    {
        id: 33,
        favourite: false,
        SongName: "Zehnaseeb",
        artist: "Vishal-Shekhar,Chinmayi Sripada,Shekhar Ravjiani,Vishal-Shekhar",
        song: "https://firebasestorage.googleapis.com/v0/b/react-music-player-5aaa7.appspot.com/o/Songs%2FHalki-Halki-(pagalworldsongs.co.in).mp3?alt=media&token=5c88f85a-be90-4b09-881a-9168327662b1",
        img_src: "https://firebasestorage.googleapis.com/v0/b/react-music-player-5aaa7.appspot.com/o/images%2Fzehnaseeb.jpg?alt=media&token=3716fb26-5cb0-480e-b719-26209506d144",
        genre: 'bollywood',
        movieName:"Hasee Toh Phasee",
    },
    {
        id: 34,
        favourite: false,
        SongName: "Vele",
        artist: "Vishal-Shekhar,Vishal Dadlani,Shekhar Ravjiani,Vishal-Shekhar",
        song: "https://firebasestorage.googleapis.com/v0/b/react-music-player-5aaa7.appspot.com/o/Songs%2FVele-(pagalworldsongs.co.in).mp3?alt=media&token=b4aa20fb-c829-46e3-ad64-8260fc3ca9ce",
        img_src: "https://firebasestorage.googleapis.com/v0/b/react-music-player-5aaa7.appspot.com/o/images%2Fvele%20vele.jph.jfif?alt=media&token=032a3a58-fcbe-4455-9e26-52122070191d",
        genre: 'bollywood',
        movieName:"Student of the Year",
    },
    {
        id: 35,
        favourite: false,
        SongName: "London Thumakda",
        artist: "Labh Janjua,Neha Kakkar,Sonu Kakkar",
        song: "https://firebasestorage.googleapis.com/v0/b/react-music-player-5aaa7.appspot.com/o/Songs%2FLondon-Thumakda-(pagalworldsongs.co.in).mp3?alt=media&token=5586c45c-46cb-4e83-8e53-f499ea7ec015",
        img_src: "https://firebasestorage.googleapis.com/v0/b/react-music-player-5aaa7.appspot.com/o/images%2Flondon-thumakda.jpg?alt=media&token=2d3d487e-fdd3-4ee1-91e7-4c2fb8eb0e11",
        genre: 'bollywood',
        movieName:"Queen",
    },
    {
        id: 36,
        favourite: false,
        SongName: "The Breakup Song",
        artist: "Badshah,Arijit Singh,Nakash Aziz,Jonita Gandhi,Pritam Chakraborty,Arijit Singh,Pritam Chakraborty,Pritam Chakraborty,Pritam Chakraborty,Jonita Gandhi,Nakash Aziz,Badshah",
        song: "https://firebasestorage.googleapis.com/v0/b/react-music-player-5aaa7.appspot.com/o/Songs%2FThe-Breakup-Song-(pagalworldsongs.co.in).mp3?alt=media&token=bc665645-20f3-4d8a-92d3-7773a0a40fd9",
        img_src: "https://firebasestorage.googleapis.com/v0/b/react-music-player-5aaa7.appspot.com/o/images%2Fbreakup%20song.jpg?alt=media&token=a194a3c2-5437-43a0-ac83-089330816a64",
        genre: 'bollywood',
        movieName:"Ae Dil Hai Mushkil",
    },
    {
        id: 37,
        favourite: false,
        SongName: "Fikar Not",
        artist: "Antara Mitra,Nakash Aziz,Amit Mishra,Amitabh Bhattacharya,Pritam Chakraborty,Dev Negi,Sreerama Chandra Mynampati",
        song: "https://firebasestorage.googleapis.com/v0/b/react-music-player-5aaa7.appspot.com/o/Songs%2FFikar-Not-b-Chhichhore-(pagalworldsongs.co.in).mp3?alt=media&token=71985a9f-e78b-4c33-87a3-cce46aafe184",
        img_src: "https://firebasestorage.googleapis.com/v0/b/react-music-player-5aaa7.appspot.com/o/images%2Ffikar%20not.jpg?alt=media&token=e57937c4-9871-47c5-8b7a-bb54b2aeea0d",
        genre: 'bollywood',
        movieName:"Chhichhore",
    },
    {
        id: 38,
        favourite: false,
        SongName: "Cutiepie",
        artist: "Pardeep Singh Sran,Pritam Chakraborty,Nakash Aziz,Pardeep Singh Sran & Nakash Aziz,Pritam",
        song: "https://firebasestorage.googleapis.com/v0/b/react-music-player-5aaa7.appspot.com/o/Songs%2FCutiepie-(Ae-Dil-Hai-Mushkil)-(pagalworldsongs.co.in).mp3?alt=media&token=a60f20d3-09d3-4b76-ab67-3feebad13419",
        img_src: "https://firebasestorage.googleapis.com/v0/b/react-music-player-5aaa7.appspot.com/o/images%2FCutiepie.jpg?alt=media&token=80d32d29-fe6a-44d9-ad55-c880da76c031",
        genre: 'bollywood',
        movieName:"Ae Dil Hai Mushkil ",
    },
]

export { Songs };